"""create_users_table

Revision ID: af30697a6297
Revises: 02efdd7ddf94
Create Date: 2026-04-05 20:54:05.816884

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'af30697a6297'
down_revision: Union[str, Sequence[str], None] = '02efdd7ddf94'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='app'
    )
    op.create_index(op.f('ix_app_users_email'), 'users', ['email'], unique=True, schema='app')
    op.create_index(op.f('ix_app_users_id'), 'users', ['id'], unique=False, schema='app')
    op.create_table('agents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('instruction', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['app.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='app'
    )
    op.create_index(op.f('ix_app_agents_id'), 'agents', ['id'], unique=False, schema='app')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_app_agents_id'), table_name='agents', schema='app')
    op.drop_table('agents', schema='app')
    op.drop_index(op.f('ix_app_users_id'), table_name='users', schema='app')
    op.drop_index(op.f('ix_app_users_email'), table_name='users', schema='app')
    op.drop_table('users', schema='app')
    # ### end Alembic commands ###
