"""create_users_table

Revision ID: af30697a6297
Revises: 02efdd7ddf94
Create Date: 2026-04-05 20:54:05.816884

"""

from typing import Sequence, Union


import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'af30697a6297'
down_revision: Union[str, Sequence[str], None] = '02efdd7ddf94'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'users',
        sa.Column(
            'id', 
            postgresql.UUID(as_uuid=True), 
            primary_key=True, 
            server_default=sa.text('gen_random_uuid()')
        ),
        sa.Column('full_name', sa.String(), nullable=False),
        sa.Column('email', sa.String(), nullable=False),
        sa.Column('hashed_password', sa.String(), nullable=False),
        sa.Column('is_active', sa.Boolean(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        schema='app',
    )
    op.create_index(
        op.f('ix_app_users_email'), 'users', ['email'], unique=True, schema='app'
    )
    op.create_index(
        op.f('ix_app_users_id'), 'users', ['id'], unique=False, schema='app'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('agents', schema='app')
    op.drop_index(op.f('ix_app_users_id'), table_name='users', schema='app')
    op.drop_index(op.f('ix_app_users_email'), table_name='users', schema='app')
    # ### end Alembic commands ###
